apiVersion: v1
items:
- apiVersion: serving.kserve.io/v1alpha1
  kind: ServingRuntime
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"serving.kserve.io/v1alpha1","kind":"ServingRuntime","metadata":{"annotations":{"opendatahub.io/template-display-name":"ServingRuntime for vLLM | Topsail"},"labels":{"opendatahub.io/dashboard":"true"},"name":"mixtral-8x7b-vllm-servingruntime","namespace":"mixtral-serve"},"spec":{"builtInAdapter":{"modelLoadingTimeoutMillis":90000},"containers":[{"args":["--model=/mnt/models/","--download-dir=/models-cache","--port=8080"],"image":"quay.io/opendatahub/vllm:fast-ibm-nightly-2024-05-01","name":"kserve-container","ports":[{"containerPort":8080,"name":"http1","protocol":"TCP"}],"volumeMounts":[{"mountPath":"/home/vllm","name":"home"},{"mountPath":"/.cache","name":"cache"},{"mountPath":"/.config","name":"config"}]}],"multiModel":false,"supportedModelFormats":[{"autoSelect":true,"name":"pytorch"}],"volumes":[{"emptyDir":{},"name":"home"},{"emptyDir":{},"name":"cache"},{"emptyDir":{},"name":"config"}]}}
      opendatahub.io/template-display-name: ServingRuntime for vLLM | Topsail
    labels:
      opendatahub.io/dashboard: "true"
    name: mixtral-8x7b-vllm-servingruntime
    namespace: mixtral-serve
  spec:
    builtInAdapter:
      modelLoadingTimeoutMillis: 90000
    containers:
    - args:
      - --model=/mnt/models/
      - --download-dir=/models-cache
      - --port=8080
      image: quay.io/modh/vllm@sha256:2e7f97b69d6e0aa7366ee6a841a7e709829136a143608bee859b1fe700c36d31
      name: kserve-container
      ports:
      - containerPort: 8080
        name: http1
        protocol: TCP
      volumeMounts:
      - mountPath: /home/vllm
        name: home
      - mountPath: /.cache
        name: cache
      - mountPath: /.config
        name: config
    multiModel: false
    supportedModelFormats:
    - autoSelect: true
      name: pytorch
    volumes:
    - emptyDir: {}
      name: home
    - emptyDir: {}
      name: cache
    - emptyDir: {}
      name: config
- apiVersion: serving.kserve.io/v1beta1
  kind: InferenceService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{"serving.kserve.io/deploymentMode":"RawDeployment","serving.kserve.io/enable-prometheus-scraping":"true"},"labels":{"opendatahub.io/dashboard":"true"},"name":"mixtral-8x7b-isvc","namespace":"mixtral-serve"},"spec":{"predictor":{"minReplicas":1,"model":{"args":["--dtype=bfloat16","--tensor-parallel-size=4","--max-model-len=4096"],"modelFormat":{"name":"pytorch"},"resources":{"limits":{"nvidia.com/gpu":"4"},"requests":{"cpu":"8","memory":"40Gi","nvidia.com/gpu":"4"}},"runtime":"mixtral-8x7b-vllm-servingruntime","storage":{"key":"aws-connection-odf","path":"models/mixtral-8x7b-v0.1/"},"storageUri":"s3://override","volumeMounts":[{"mountPath":"/dev/shm","name":"shared-memory"},{"mountPath":"/tmp","name":"tmp"},{"mountPath":"/home/vllm","name":"home"}]},"serviceAccountName":"sa","volumes":[{"emptyDir":{"medium":"Memory","sizeLimit":"16Gi"},"name":"shared-memory"},{"emptyDir":{},"name":"tmp"},{"emptyDir":{},"name":"home"}]}}}
      serving.kserve.io/deploymentMode: RawDeployment
      serving.kserve.io/enable-prometheus-scraping: "true"
    labels:
      opendatahub.io/dashboard: "true"
    name: mixtral-8x7b-isvc
    namespace: mixtral-serve
  spec:
    predictor:
      minReplicas: 1
      model:
        args:
        - --dtype=bfloat16
        - --tensor-parallel-size=4
        - --max-model-len=4096
        modelFormat:
          name: pytorch
        resources:
          limits:
            nvidia.com/gpu: "4"
          requests:
            cpu: "8"
            memory: 40Gi
            nvidia.com/gpu: "4"
        runtime: mixtral-8x7b-vllm-servingruntime
        storage:
          key: aws-connection-odf
          path: models/mixtral-8x7b-v0.1/
        volumeMounts:
        - mountPath: /dev/shm
          name: shared-memory
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/vllm
          name: home
      serviceAccountName: default
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 16Gi
        name: shared-memory
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: home
kind: List
metadata: {}
