FROM registry.access.redhat.com/ubi9/python-311:latest

RUN pip install --no-cache-dir instructlab-training@git+https://github.com/instructlab/training.git

USER 1001

# Set HF_HOME to volatile location. We do not preserve cache etc over restarts with this container.
# https://huggingface.co/docs/huggingface_hub/en/guides/manage-cache
ENV HF_HOME="/tmp"

# Make sure the containerfile has access to the run_data_processing.py file
COPY run_data_processing.py .

# Required to set default runtime as Python for Kubeflow Pipelines
CMD ["python3.11"]
