apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: ilab-torchrun-test
  namespace: ikolchin
spec:
  nprocPerNode: "2"
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
            - args:
                - |-
                  python3.11 -u "run.py" --nnodes 3 --nproc_per_node 2 --node_rank $(RANK) --rdzv_endpoint $(MASTER_ADDR):$(MASTER_PORT)
              command:
                - /bin/bash
                - '-c'
                - '--'
              image: 'quay.io/michaelclifford/test-train:0.0.15'
              name: pytorch
              resources:
                limits:
                  nvidia.com/gpu: 2
                requests:
                  nvidia.com/gpu: 2
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
            - args:
                - |-
                  python3.11 -u "run.py" --nnodes 3 --nproc_per_node 2 --node_rank $(RANK) --rdzv_endpoint $(MASTER_ADDR):$(MASTER_PORT)
              command:
                - /bin/bash
                - '-c'
                - '--'
              image: 'quay.io/michaelclifford/test-train:0.0.15'
              name: pytorch
              resources:
                limits:
                  nvidia.com/gpu: 2
                requests:
                  nvidia.com/gpu: 2
  runPolicy:
    suspend: false
